build:
  verbosity: minimal

clone_depth: 30

build_script :
- '%BASH_PATH% -lc "g++ --version"'
- '%BASH_PATH% -lc "cd $APPVEYOR_BUILD_FOLDER; ./test_byacc.sh "'
- DIR

cache :
- usr

environment :
 MSYSTEM: MINGW64 
 BASH_PATH: C:\msys64\usr\bin\bash

 
